# -*- coding: utf-8 -*-
"""Ass_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qpq5pV_PTt_0Vt02xpuyGC11QL7N1IOR
"""

def print_positive_numbers(numbers):
    positive_numbers = [num for num in numbers if num > 0]
    print(positive_numbers)

# Example inputs
list1 = [12, -7, 5, 64, -14]
list2 = [12, 14, -95, 3]

# Output
print("Input:", list1)
print("Output:", end=" ")
print_positive_numbers(list1)

print("\nInput:", list2)
print("Output:", end=" ")
print_positive_numbers(list2)

