# -*- coding: utf-8 -*-
"""Ass_1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YOO2jqnge0iNxYFHX2WKDGEv4HwyEh3l
"""

x=float(input("Enter radius"))
area=3.14*(x**2)
print(area)

def file_extension(file):
  split=file.split(".")
  if len(split)>1:
    extension=split[-1]
    return extension
def main():
  file_name=input("Enter the file name:")
  extension=file_extension(file_name)
  print("The file extension is:",extension)
main()

