# -*- coding: utf-8 -*-
"""Ass_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XcTSNighJ1XrOpNiNpe8NPGjJGqFmoZG
"""

def most_frequent(string):
    frequency = {}
    for char in string:
        if char in frequency:
            frequency[char] += 1
        else:
            frequency[char] = 1
    sorted_frequency = dict(sorted(frequency.items(), key=lambda item: item[1], reverse=True))
    for char, freq in sorted_frequency.items():
        print(f"{char} = {freq:02d}")
input_string = input("Please enter a string: ")
most_frequent(input_string)

