# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UjMsmsyVxW2qFh3-1b31R0gJqoqR0am9
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
agoda_url="https://www.agoda.com/"
req=requests.get(agoda_url)
content = req.content
soup = BeautifulSoup(content, "html.parser")
all_hotels = soup.find_all ("div", {"class":"PropertyCardItem"})
scraped_info_list = []
for hotel in all_hotels:
  hotel_name = hotel.find("h3",{"class":"hotel_name"}).text
  hotel_address = hotel.find("span", {"class":"sc-jrAgrp"}).text
  hotel_rating = hotel.find("img", {"class":"sc-bdfBwQ"}).text
  hotel_price = hotel.find("span", {"class":"ListPropertyCard_Prices"}).text
  print(hotel_name , hotel_address , hotel_rating , hotel_price_)
  scraped_info_list.append(project_name)
dataframe = pd.DataFrame(scraped_info_list)
dataframe.to_csv("agoda.csv")

